{% set name = "rodeometric" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rodeometric-{{ version }}.tar.gz
  sha256: d3b0c870b618458681e71c4443bc36be1355eea46eae8b68b79209e6cbc575c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - scikit-learn >=1.0.2

test:
  imports:
    - rodeo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FeliMe/RoDeO
  summary: 'Robust Detection Outcome: A Metric for Pathology Detection in Medical Images'
  description: |
    RoDeO is an easy to use object detection metric useful for
    (but not limited to) applications in medical imaging, such as
    pathology detection in Chest X-ray images.
    It evaluates three sources of errors (misclassification,
    faulty localization, and shape mismatch) separately and combines them to
    one score.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/FeliMe/RoDeO

extra:
  recipe-maintainers:
    - FeliMe
    - philip-mueller
